### ISSUE TITLE
Issues in search function, piwebapi

### ISSUE THREAD

**Issue by ingefosse** [equinor/tagreader-python#125]
Lately I get this error message when I search for tags using method piwebapi (not for aspenone), regardless of plant and tags/descriptions. Any suggestions to what might be wrong? 

![image](https://user-images.githubusercontent.com/60174614/185884696-4f324b38-958d-4d65-aa7c-b3e41cbc1fe3.png)

**Comment by einarsi** [comment]
There is a problem with the PI database that needs to be fixed. I'll message you directly.
