### ISSUE TITLE
Normally poetry.lock is not commited to git for libraries

### ISSUE THREAD

**Issue by asmfstatoil** [equinor/tagreader-python#187]
ref: 
https://github.com/python-poetry/poetry/issues/7488

**Comment by mortendaehli** [comment]
@asmfstatoil, thank you for the feedback. The lock file is used for development and security purposes and does not have any effect on the published package on PyPI. The requirements when installing packages from PyPi is resolved based on the pyproject.toml and not poetry.lock.

Long story short. We want to share the poetry.lock file between developers and to pin dependencies when scanning for vulnerabilities.
