### ISSUE TITLE
Failing to install version 4.0.1 on mac m1 with python 3.11.2 due to issues with tables

### ISSUE THREAD

**Issue by asmfstatoil** [equinor/tagreader-python#202]
Downloading tables-3.8.0.tar.gz (8.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 8.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      ld: library not found for -lhdf5
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.11.2 (main, Mar  8 2023, 10:10:03) [Clang 14.0.0 (clang-1400.0.29.202)]
      * Found cython 0.29.35
      * USE_PKGCONFIG: True
      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.
      [end of output]

**Comment by mortendaehli** [comment]
@asmfstatoil, than you for the feedback. Are you running macOS?

This is an issue related to HDF5, used for caching, which is not installed "automagically" on macOS. I've removed the requirement when using ARM64 architecture, which is used by MacBooks the last 2+ years.

v4.0.3 has been released. Please report back if the problem persists.

Btw. if you just want to install HDF5 to use the cache functionality, you can follow the pytables guide here: https://www.pytables.org/usersguide/installation.html

**Comment by asmfstatoil** [comment]
Tested and working.
