### ISSUE TITLE
Resolve Snyk Code identified vulnerabilities

### ISSUE THREAD

**Issue by mortendaehli** [equinor/tagreader-python#217]
Ref.:
<img width="1270" alt="Screenshot 2023-06-15 at 15 46 29" src="https://github.com/equinor/tagreader-python/assets/16227584/58763f9b-6aee-4b58-b89d-97fd728dc411">

Definition of Done:
- Resolve issues
- Remove "continue-on-error: true" from snyk-pipeline

**Comment by asmfstatoil** [comment]
Item 1 and 2 refers to #253 
Item 3-4-5 are probably not relevant. This is just a wrapper package and does not specify write access to the db.
