### ISSUE TITLE
v4.2.0 giving unexpected errors

### ISSUE THREAD

**Issue by Jfoul** [equinor/tagreader-python#231]
# Error description

I am running tagreader v4.2.0 with the same setup as v4.1.4, and I am unable to run my script. 
I have not changed anything when I call upon tagreader between the versions. In either case I am using a list for my tags (and I get the same error both with PI and Aspen tags). 

~~~
df = c.read(tag_list, start_date, end_date, sample_freq)
~~~

I see in https://github.com/equinor/tagreader-python/pull/229/files, the error am I obtaining relates back this. I don't see it, but potentially I need to call upon tagreader differently?
The error screenshot can be seen attached. 

![image](https://github.com/equinor/tagreader-python/assets/98525541/dbd19140-0652-4ef5-9957-0514fa0a3664)

# System
Have tried in both Linux and Windows. 
Python 3.9 and 3.10

**Comment by mortendaehli** [comment]
Thank you for reporting this issue. We are working on a fix right now :)
