### ISSUE TITLE
AttributeError: 'str' object has  no attribute 'localize' with c.read()

### ISSUE THREAD

**Issue by DWMorrow** [equinor/tagreader-python#246]
tagreader version is 4.2.3
python version 3.10.12

Extracting values using a specific time zone is returning an error. I've copied something like the below, but am using "US/Eastern". When not setting tz="US/Eastern", c.read() works, and the default time zone is UTC+2

```
import tagreader
c = tagreader.IMSClient("PINO", "pi", tz="US/Central")  # Force output data to Houston time
c.connect()
start_time = "01-Jan-2022 00:00:00"
end_time = "01-Feb-2022 00:00:00"
df = c.read([f"{tag}"], start_time, end_time, ts=f"{ts_val})

```

The error is populating in tagreader\utils.py:88
```
date_stamp = convert_to_pydatetime(date_stamp)
if not date_stamp.tzinfo:
  date_stamp = tz.localize(date_stamp)
```

**Comment by mortendaehli** [comment]
@DWMorrow, thank you for reporting this issue. We will look at this shortly.
