### ISSUE TITLE
Update certificate handling for Equinor

### ISSUE THREAD

**Issue by einarsi** [equinor/tagreader-python#253]
New certificates are being issued and the old ones will eventually expire. The existing solution for importing a specific certificate (the old root cert) specified by hash to certifi must therefore be updated. Perhaps amend `add_statoil_root_certificate()` to support both the old and the new certificate? 

I also suggest to consider adding functionality for fetching the certificate directly from pki.equinor.com. That would make things easier for Linux users and others using tagreader in environments without pre-existing Equinor certificates (e.g. Radix).

**Comment by asmfstatoil** [comment]
I think the update of pi webapi certificates just broke tagreader and the add_statoil_root_certificate function

**Comment by asmfstatoil** [comment]
#271
