### ISSUE TITLE
Client.read input 

### ISSUE THREAD

**Issue by asmfstatoil** [equinor/tagreader-python#259]
Input checking for ts is a bit too strict. Input ts is not required for read types snapshot and raw.

Also there is no need to 

`raise ValueError(
                "ts needs to be either a None, timedelta or and integer (number of seconds)."
                f" Given type: {type(ts)}"
            )`

just because inputtype is float. A conversion from float to int is nicer.

Also in same function, are you sure that input end is required for snapshots? If not, should this line be indented one more level? 
`        if end:
            end = ensure_datetime_with_tz(end, tz=self.tz)`

**Comment by mortendaehli** [comment]
Hi @asmfstatoil,

Thanks for notifying us. I'll allow float converted to int for timedelta and release it ASAP.

I'm not sure if I understand you correctly for the last part. End is not required, so it should be Okay with respect to snapshot. Or am I mistaken?
