### ISSUE TITLE
Add option to return status

### ISSUE THREAD

**Issue by einarsi** [equinor/tagreader-python#34]
**Aspen IP.21 ODBC** returns a single status value which is 
  - 0: Good
  - 1: Suspect
  - 2: Bad
  - 4: Good/M (history has been modified)
  - 5: Suspect/M (history has been modified)
  - 6: Bad/M (history has been modified)

**PI ODBC and Web API** can return three booleans that may be relevant: 
  - Good (or IsGood)
  - Questionable
  - Substituted
(Also Annotated, but probably not relevant here)

**PI ODBC** can also return Status, which is documented [here](https://techsupport.osisoft.com/Documentation/PI-AF-SDK/html/T_OSIsoft_AF_Asset_AFValueStatus.htm). It is somewhat more detailed, but probably unnecessarily so.

Assuming AspenOne can provide the same as IP.21 ODBC,, an initial suggestion is to combine the three booleans from PI into a numerical value corresponding to Aspen IP.21 ODBC nomenclature. Assuming that Good and Questionable are mutually exclusive: Status = Questionable + 2*(1-Good) + 4 * Substituted

**Comment by torlid** [comment]
Went here to add this issue, but it was already posted :-)

Maybe a "collect Good data only" parameter could be one of several good solutions to solve this problem. 

Looking forward to having this new feature:

**Comment by einarsi** [comment]
Aspen Web API: The field "Level" seems to map 1:1 to status from ODBC, at least for 0, 2, 4 and 6.

**Comment by einarsi** [comment]
Seems as if PI ODBC has the following:
status (INT): 0 for good, can be both positive and negative
questionable (BOOL)
substituted (BOOL)

To conform with the above, I'll just replace any status value != 0 with 1.

**Comment by einarsi** [comment]
Implemented functionality with PR #63
