### ISSUE TITLE
piwebapi does not work in version 6.0.0

### ISSUE THREAD

**Issue by kjeel-dev** [equinor/tagreader-python#376]
piwebapi does not work in version 6.0.0, please see the error messages below.
Can connect to client, not allowed to read tags. This used to work before. aspenone works just fine.

![image](https://github.com/user-attachments/assets/577e3682-6c38-4a9a-8fcc-b96567879a17)

**Comment by Asgmel03** [comment]
This was probably due to the updates not being rolled out to the piwebapi yet. Is it working now?

**Comment by kjeel-dev** [comment]
Yes, thanks, it works now.
