### ISSUE TITLE
Data format returned from .read function

### ISSUE THREAD

**Issue by ingefosse** [equinor/tagreader-python#83]
The .read function (tags, start_time, end_time, time_interval etc.) seems to return data as a list, one element per tag, with all information. When I want to write the data to a .csv file I would like to convert it to a format that is easier to work with - e.g. a "time" column with the time data and one column "tag-name" with the tag values. Any tips?

**Comment by einarsi** [comment]
The .read() method returns a [Pandas DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html) with timestamp as index and one column per tag. DataFrames are very convenient and powerful to work with. You can write the dataframe directly to a csv file by calling the [.to_csv()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html) method.
