### ISSUE TITLE
Data format returned from search function

### ISSUE THREAD

**Issue by ingefosse** [equinor/tagreader-python#87]
Hi - seems that the tag search function returns a list with entities (tag + description). I would like to like to grab the tags only in an easy way - and then perhaps get units and get descriptions etc. later. Would it be possible not to combine tag and description in one list entity, or is it an easy way for users to extract the tag from the return of the search function?

**Comment by einarsi** [comment]
Hi Inge,
The data is returned as a list of tuples where the first element in each tuple is the tag and the second is the description. If you have the search results in `result`, you can easily extract the tags into a list like so:
```
tags = [x[0] for x in result]
```
